#!/bin/sh
#
# Created at: 2020 Feb 5 11:00
#
# Output is custom formatted info.

# Funcs
flatten() { 
	[ "$1" = "" ] &&
		sed '/^\s*$/d' | tr -d '\n' | fold -sw 40 ||
		sed '/^\s*$/d' | sed "N;s/\n/$1/" | tr '\n' " " | fold -sw 40;
}

# Vars
[ "$1" = "" ] && exit 2;
url="https://dictionary.cambridge.org/dictionary/english/$(echo $1 | tr ' ' '-')"
dir=${HOME}/.cache/cambridge
file=$dir/$(echo $1 | tr ' ' '-').html

# Preparing the environment
mkdir -p $dir

# Selectors
phrase='.dhw text{}' # TODO FIX Not stable
type_='.posgram text{}' # TODO FIX Not stable
pronunciation='.uk .ipa.dipa.lpr-2.lpl-1 text{}' #TODO utf-8 problem
definition='.def.ddef_d.db text{}' # TODO Get one uniq definition.
level='.epp-xref.dxref text{}' #DONE

# Request
if ! [ -f $file ]; then
	curl -s $url -H 'Accept-Encoding: br, deflate' |
		pup '.entry-body__el' > $file || exit 2;
fi

# Result
if [ "$(cat $file)" = "" ]; then  
	>&2 echo "$0: no such phrase in cambridge dictionary";
	exit 2;
else
	## Level
	tput dim;
	cat $file | pup -p $level | grep -o '[A-z0-9]\+' | sort|uniq | flatten ' ';
	tput sgr0;
	
	## Phrase
	tput bold; tput setaf 2;
	cat $file | pup -p $phrase | grep -o '[A-z0-9]\+' | sort|uniq | flatten ', ';
	tput sgr0;
	
	# Pronunciation
	tput setaf 3;
	cat $file | pup -p $pronunciation | sed 's/\s/ /g' | sort|uniq | flatten;
	tput sgr0;
	
	## Type
	printf ' ';
	tput dim;
	cat $file | pup -p $type_ | grep -o '[A-z]\+' | sed '/^.$/d' | sort|uniq |
		flatten ', ';
	tput sgr0; echo;
	
	## Definition
	echo
	#TODO Replace grep command with sed to delete white spaces and replace two
	#     empty lines with one empty line. Finally head -n 1 from definitions.
	#     Or find a limit option for pup to limit result with 1.
	cat $file | pup $definition | grep -o "[A-z'\"]\+" | tr '\n' ' ' | flatten;
	echo;
fi
